//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 03:58:12 PM CEST 
//


package com.web.client.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="entite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://univ.fr/stb}contact"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlRootElement(name = "client")
@XmlAccessorType(XmlAccessType.NONE)
public class Client {

	@XmlElement(required = true)
	protected String entite;
	@XmlElement(required = true)
	protected Contact contact;

 




	public Client(String entite, Contact contact) {
		super();
		this.entite = entite;
		this.contact = contact;
	}

	public Client() {
		super();
	}



	/**
	 * Gets the value of the entite property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */

	public String getEntite() {
		return entite;
	}

	
	/**
	 * Sets the value of the entite property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setEntite(String value) {
		this.entite = value;
	}

	/**
	 * Gets the value of the contact property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Contact }
	 *     
	 */
	public Contact getContact() {
		return contact;
	}

	/**
	 * Sets the value of the contact property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Contact }
	 *     
	 */
	public void setContact(Contact value) {
		this.contact = value;
	}

}
