//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 03:58:12 PM CEST 
//


package com.web.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="nom" type="{http://univ.fr/stb}genderType"/>
 *         &lt;element name="prenom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 	
 */

@XmlRootElement(name = "equipe")
@XmlAccessorType(XmlAccessType.NONE)
public class Equipe {
	

	@XmlElement(required = true)
	protected GenderType nom;
	
	@XmlElement(required = true)
	protected String prenom;
	
	

	public Equipe() {
		super();
	}

	public Equipe(GenderType nom, String prenom) {
		super();
		this.nom = nom;
		this.prenom = prenom;
	}

	
	


	/**
	 * Gets the value of the nom property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link GenderType }
	 *     
	 */
	
	public GenderType getNom() {
		return nom;
	}

	/**
	 * Sets the value of the nom property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link GenderType }
	 *     
	 */
	public void setNom(GenderType value) {
		this.nom = value;
	}

	/**
	 * Gets the value of the prenom property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */

	public String getPrenom() {
		return prenom;
	}

	/**
	 * Sets the value of the prenom property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPrenom(String value) {
		this.prenom = value;
	}

}
