//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 03:58:12 PM CEST 
//


package com.web.client.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ.fr/stb}titre"/>
 *         &lt;element ref="{http://univ.fr/stb}version"/>
 *         &lt;element ref="{http://univ.fr/stb}date"/>
 *         &lt;element ref="{http://univ.fr/stb}description"/>
 *         &lt;element ref="{http://univ.fr/stb}client"/>
 *         &lt;element ref="{http://univ.fr/stb}equipe" maxOccurs="7" minOccurs="2"/>
 *         &lt;element ref="{http://univ.fr/stb}fonctionnalite" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://univ.fr/stb}commentaire" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titre",
    "version",
    "date",
    "description",
    "client",
    "equipe",
    "fonctionnalite",
    "commentaire"
})
@XmlRootElement(name = "stb")
public class Stb {

    @XmlElement( required = true)
    protected String titre;
    @XmlElement(required = true, defaultValue = "0.1")
    protected String version;
    @XmlElement( required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement( required = true)
    protected String description;
    @XmlElement(required = true)
    protected Client client;
    @XmlElement( required = true)
    protected List<Equipe> equipe;
    @XmlElement( required = true)
    protected List<Fonctionnalite> fonctionnalite;
    @XmlElement()
    protected List<String> commentaire;
    /**
     * Gets the value of the titre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitre() {
        return titre;
    }

    public Stb(String titre, String version, XMLGregorianCalendar date, String description, Client client,
			List<Equipe> equipe, List<Fonctionnalite> fonctionnalite, List<String> commentaire) {
		super();
		this.titre = titre;
		this.version = version;
		this.date = date;
		this.description = description;
		this.client = client;
		this.equipe = equipe;
		this.fonctionnalite = fonctionnalite;
		this.commentaire = commentaire;
	}

	public Stb() {
		super();
	}

	/**
     * Sets the value of the titre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitre(String value) {
        this.titre = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link Client }
     *     
     */
    public Client getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link Client }
     *     
     */
    public void setClient(Client value) {
        this.client = value;
    }

    /**
     * Gets the value of the equipe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equipe }
     * 
     * 
     */
    public List<Equipe> getEquipe() {
        if (equipe == null) {
            equipe = new ArrayList<Equipe>();
        }
        return this.equipe;
    }

    /**
     * Gets the value of the fonctionnalite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fonctionnalite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFonctionnalite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fonctionnalite }
     * 
     * 
     */
    public List<Fonctionnalite> getFonctionnalite() {
        if (fonctionnalite == null) {
            fonctionnalite = new ArrayList<Fonctionnalite>();
        }
        return this.fonctionnalite;
    }

    /**
     * Gets the value of the commentaire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentaire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentaire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCommentaire() {
        if (commentaire == null) {
            commentaire = new ArrayList<String>();
        }
        return this.commentaire;
    }

}
